### ISSUE TITLE
Imager crashes when using multi-spectral image cubes

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#117]
```
Traceback (most recent call last):
  File "/home/christoph/development/SKA/karabo/test/test_source_detection.py", line 70, in test_create_detection_from_ms
    convolved, restored, residual = imager.imaging_rascil()
  File "/home/christoph/development/SKA/karabo/Imaging/imager.py", line 227, in imaging_rascil
    restored = image_gather_channels(restored)
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/rascil/processing_components/image/gather_scatter.py", line 185, in image_gather_channels
    return xarray.concat(image_list, dim="frequency")
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/xarray/core/concat.py", line 238, in concat
    return f(
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/xarray/core/concat.py", line 517, in _dataset_concat
    combined = concat_vars(vars, dim, positions, combine_attrs=combine_attrs)
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/xarray/core/variable.py", line 2999, in concat
    return Variable.concat(variables, dim, positions, shortcut, combine_attrs)
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/xarray/core/variable.py", line 1902, in concat
    data = duck_array_ops.concatenate(arrays, axis=axis)
  File "/home/christoph/anaconda3/envs/karabo_dev_env/lib/python3.9/site-packages/xarray/core/duck_array_ops.py", line 286, in concatenate
    return _concatenate(as_shared_dtype(arrays), axis=axis)
  File "<__array_function__ internals>", line 180, in concatenate
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 66.5 GiB for an array with shape (16, 1, 23685, 23559) and data type float64
```

**Comment by deiruch** [comment]
I believe this could be fixed by using code similar to the `restore_cube` function: https://ska-telescope.gitlab.io/external/rascil/_modules/rascil/processing_components/image/deconvolution.html#restore_cube.

The point is that we have to make sure that `image_scatter_channels` is called first.

**Comment by kenfus** [comment]
For me the test fails at `        simulation.run()` in the function `run_simulation` with the following error:

```
Fatal Python error: Segmentation fault

Thread 0x00007ff79b7fe700 (most recent call first):
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 316 in wait
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 581 in wait
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 261 in _on_run
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007ff79bfff700 (most recent call first):
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 316 in wait
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 581 in wait
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 215 in _on_run
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007ff7a8d58700 (most recent call first):
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 312 in wait
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 581 in wait
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_timeout.py", line 43 in _on_run
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007ff7a9599700 (most recent call first):
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 204 in _read_line
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 222 in _on_run
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007ff7a9d9a700 (most recent call first):
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 316 in wait
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/queue.py", line 180 in get
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 367 in _on_run
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 49 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/threading.py", line 937 in _bootstrap

Current thread 0x00007ff7abbc8740 (most recent call first):
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/oskar/settings_tree.py", line 215 in to_telescope
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/oskar/interferometer.py", line 166 in check_init
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/oskar/interferometer.py", line 290 in run
  File "/home/kenfus/Karabo/Karabo-Pipeline/karabo/simulation/interferometer.py", line 121 in run_simulation
  File "/home/kenfus/Karabo/Karabo-Pipeline/karabo/test/test_source_detection.py", line 68 in test_create_detection_from_ms
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/unittest/case.py", line 550 in _callTestMethod
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/unittest/case.py", line 592 in run
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/unittest/case.py", line 651 in __call__
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/unittest.py", line 327 in runtest
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 338 in from_call
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/main.py", line 322 in _main
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124 in _run_code
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238 in _run_module_as_main
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317 in run_module
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430 in main
  File "/home/kenfus/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39 in <module>
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/runpy.py", line 87 in _run_code
  File "/home/kenfus/miniconda3/envs/karabo_dev_env/lib/python3.9/runpy.py", line 197 in _run_module_as_main
```

**Comment by kenfus** [comment]
Update: Thanks to @rohitcbscient the test now works. However, I'm now also blocked by #146 with this

**Comment by kenfus** [comment]
I fixed the segmentation error and now the test works for me without errors, so I guess we can close this? I also have only 16 GB of Ram on my machine.

**Comment by kenfus** [comment]
Current dimension output of `imaging_rascil`:

```
      # Print shapes
      print("Convolved shape: ", convolved.get_dimensions_of_image())
      print("Restored shape: ", restored.get_dimensions_of_image())
      print("Residual shape: ", residual.get_dimensions_of_image())
    
```

**Comment by kenfus** [comment]
Together with @rohitcbscient I did another test. The output of the following code:
```
        simulation = InterferometerSimulation(channel_bandwidth_hz=1e6,
                                            time_average_sec=1, noise_enable=False,
                                            noise_seed="time", noise_freq="Range", noise_rms="Range",
                                            noise_start_freq=1.e9,
                                            noise_inc_freq=1.e8,
                                            noise_number_freq=24,
                                            noise_rms_start=0,
                                            noise_rms_end=0)


        observation = Observation(
            100e6,
            phase_centre_ra_deg=phasecenter[0],
            phase_centre_dec_deg=phasecenter[1],
            number_of_time_steps=1,
            frequency_increment_hz=20e6,
            number_of_channels=4
        )
    
        visibility = simulation.run_simulation(telescope, sky, observation)
        visibility.write_to_file("./result/test_dec/poisson_vis.ms")
    
        imager = Imager(
            visibility,
            ingest_vis_nchan=4,
            ingest_chan_per_blockvis=1,
            ingest_average_blockvis=True,
            imaging_npixel=2048,
            imaging_cellsize=0.0003,
            imaging_weighting="natural",
            imaging_robustness=-0.5,
        )
        convolved, restored, residual = imager.imaging_rascil()

        print("Shape convolved:", convolved.get_dimensions_of_image())
        print("Shape restored:", restored.get_dimensions_of_image())
        print("Shape residual:", residual.get_dimensions_of_image())
```

is:

```
Shape convolved: [7419, 7213, 1, 4]
Shape restored: [7419, 7213, 1, 4]
Shape residual: [7419, 7213, 1, 4]
```

For me it seems correct and can then also closed (also, no memory problems, even with 16 channels).

**Comment by deiruch** [comment]
I would've expected a shape of [2048, 2048, 1, 4] since you specify `imaging_npixel=2048`. Odd...?

**Comment by kenfus** [comment]
```
    def test_create_detection_from_ms(self):
        phasecenter = np.array([225, -65])
        sky = SkyModel.get_random_poisson_disk_sky(
            phasecenter + np.array([-5, -5]),
            phasecenter + np.array([+5, +5]),
            100,
            200,
            0.4,
        )

        # sky = SkyModel.get_GLEAM_Sky()
        # sky.filter_by_flux(0.4, 1)
        sky.plot_sky(phasecenter)
        sky.explore_sky(phasecenter, xlim=(-10, 10), ylim=(-10, 10))
    
        telescope = Telescope.get_MEERKAT_Telescope()
        # telescope.centre_longitude = 3
    
        simulation = InterferometerSimulation(
            channel_bandwidth_hz=1e6,
            time_average_sec=1
            )

        observation = Observation(
            start_frequency_hz=100e6,
            phase_centre_ra_deg=phasecenter[0],
            phase_centre_dec_deg=phasecenter[1],
            number_of_time_steps=1,
            frequency_increment_hz=20e6,
            number_of_channels=3
        )
    
        visibility = simulation.run_simulation(telescope, sky, observation)
        visibility.write_to_file("./result/test_dec/poisson_vis.ms")
    
        imager = Imager(
            visibility,
            ingest_vis_nchan=3,
            ingest_chan_per_blockvis=1,
            ingest_average_blockvis=True,
            imaging_npixel=2048,
            imaging_cellsize=0.0003,
            imaging_weighting="natural",
            imaging_robustness=-0.5,
        )
        convolved, restored, residual = imager.imaging_rascil()

        # Print shapes
        print("Convolved shape: ", convolved.get_dimensions_of_image())
        print("Restored shape: ", restored.get_dimensions_of_image())
        print("Residual shape: ", residual.get_dimensions_of_image())
```
```
Convolved shape:  [5763, 5583, 1, 3]
Restored shape:  [5763, 5583, 1, 3]
Residual shape:  [5763, 5583, 1, 3]
```

Here another example. Also, no memory issues here. I guess xarray made an update.
