### ISSUE TITLE
GPU-accelerated RASCIL WAAG

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#183]
Currently we don't use GPU-capability of RASCIL at the moment if I'm not mistaken.

According to [RASCIL documentation towards WAGG](https://ska-telescope.gitlab.io/external/rascil/RASCIL_wagg.html) the nifty-gridder [WAAG](https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda) needs to be installed manually afterwards and I don't see any steps toward this in our current [RASCIL builds](https://github.com/i4Ds/rascil-build) or anywhere in the [RASCIL](https://gitlab.com/ska-telescope/external/rascil) repository.

If available, RASCIL is able to perform gridding and degridding operations on GPU level.

**Comment by kenfus** [comment]
I wanted to time Rascil with dask vs. WAAG. However, I was unable to make WAAG run. After installing the
[CUDA Nifty Gridder](https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda), a minimal test to see if it works is as follows:

```
import cuda_nifty_gridder as cng 
cng.dirty2ms(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0)
```

for me, this fails with the following error: 

```
cuInit error (code 100): no CUDA-capable device is detected
cuda error: 100cuCtxSetCurrent error: 3cuModuleLoadData error: 3Segmentation fault
```

**Comment by kenfus** [comment]
Current status: On a laptop without cuda installed in the root-folder but only in the conda environment with `conda install cuda -c nvidia`, I have the manually set `LD_LIBRARY_PATH` to `/home/vincenzo/miniconda3/envs/karabo_dev_env/lib/` and then it finds all the needed cuda libraries. However, it does not find one: 

```Unable to open 'libcuda'. Check LD_LIBRARY_PATH.```

As read (here)[https://askubuntu.com/questions/905993/missing-libcuda-so-1-file-after-upgrading-to-newest-nvidia-driver] it seems that this file is installed when we installed the driver. However, with WSL 2 I only need to install the nvidia driver via windows, not with Linux.

**Comment by kenfus** [comment]
After installing https://anaconda.org/nvidia/cuda-toolkit and https://anaconda.org/nvidia/cuda all the necessary libraries are there. However, now it fails for me with:


```
cuInit error (code 34): (null)
cuda error: 34cuCtxSetCurrent error: 34cuModuleLoadData error: 34cuInit error (code 34): (null)
cuMemAlloc error (code 34): (null)
cuInit error (code 34): (null)
cufftPlanMany error (code 34)
Traceback (most recent call last):
  File "/home/vincenzo/ska-gridder-nifty-cuda-1/tests/unit/test_dirty2ms.py", line 160, in <module>
    test_dirty2ms_single_2D()
  File "/home/vincenzo/ska-gridder-nifty-cuda-1/tests/unit/test_dirty2ms.py", line 95, in test_dirty2ms_single_2D
    error, passThreshold = run_dirty2ms(doSingle=True, multiChannel=True, epsilon=thisEps, doWStacking = False)
  File "/home/vincenzo/ska-gridder-nifty-cuda-1/tests/unit/test_dirty2ms.py", line 73, in run_dirty2ms
    error = compareCNGandRNG(uvw, freqs, test_dirty_image, weights, imSize, pixsize_rad, epsilon, doWStacking)
  File "/home/vincenzo/ska-gridder-nifty-cuda-1/tests/unit/test_dirty2ms.py", line 19, in compareCNGandRNG
    cngVis = cng.dirty2ms(uvw, freqs, test_dirty_image, weights, pixsize_rad, pixsize_rad, 0, 0, epsilon, doWStacking, verbosity = 0)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/cuda_nifty_gridder/api.py", line 92, in dirty2ms
    ms = _cuda_nifty_gridder_lib.dirty2ms(uvw, freq, dirty, weight, pixsize_x_rad, pixsize_y_rad, epsilon, do_wstacking, verbosity)
RuntimeError: dirty2ms() failed (code 2).
```

**Comment by kenfus** [comment]
So, it seems to work when updating `LD_LIBRARY_PATH` with `$LD_LIBRARY_PATH:/usr/lib/wsl/lib`. Will try to add this to the yaml file

**Comment by kenfus** [comment]
It works currently on a fresh enviorment without any extra installations. However, I get this error currently:

```
Traceback (most recent call last):
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 190, in <module>
    main()
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 179, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "time_execution.py", line 74, in <module>
    test_create_detection_from_ms()
  File "time_execution.py", line 60, in test_create_detection_from_ms
    convolved, restored, residual = imager.imaging_rascil(
  File "/home/vincenzo/Karabo-Pipeline/karabo/imaging/imager.py", line 240, in imaging_rascil
    result = continuum_imaging_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/pipelines/pipeline_skymodel_rsexecute.py", line 392, in continuum_imaging_skymodel_list_rsexecute_workflow
    ) = ical_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/pipelines/pipeline_skymodel_rsexecute.py", line 154, in ical_skymodel_list_rsexecute_workflow
    skymodel_list = deconvolve_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/skymodel/skymodel_rsexecute.py", line 396, in deconvolve_skymodel_list_rsexecute_workflow
    deconvolve_model_imagelist = deconvolve_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 510, in deconvolve_list_rsexecute_workflow
    return deconvolve_list_singlefacet_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 457, in deconvolve_list_singlefacet_rsexecute_workflow
    clean_list = rsexecute.execute(imaging_deconvolve, nout=len(dirty_list))(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 446, in imaging_deconvolve
    comp, _ = deconvolve_list(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/processing_components/image/deconvolution.py", line 128, in deconvolve_list
    check_psf_peak(psf_list)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/processing_components/image/deconvolution.py", line 170, in check_psf_peak
    numpy.testing.assert_approx_equal(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 698, in assert_approx_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal to 6 significant digits:
check_psf_peak: PSF 0 does not have unit peak 0.9996356147582426
 ACTUAL: 0.9996356147582426
 DESIRED: 1.0
```
I guess that is something @rohitcbscient should have a look at it.

**Comment by deiruch** [comment]
Perhaps WAAG is outdated?

See:
https://gitlab.com/ska-telescope/sdp/ska-gridder-nifty-cuda/-/issues/1
https://jira.skatelescope.org/browse/SP-2181?jql=cf%5B12302%5D%20%3D%20Team_NZAPP

**Comment by kenfus** [comment]
The tests of `ska-gridder-nifty-cuda` work perfectly. Maybe we are passing somehow wrong parameters?

**Comment by kenfus** [comment]
Closed this issue because it is implemented but raises an assertion error as mentioned in #206
