### ISSUE TITLE
`check_psf_peak` of `ska-gridder-nifty-cuda` does not fail the assertion.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#206]
As mentioned in #183, the `ska-gridder-nifty-cuda` `predict_wg` fails with the following error:

```
Traceback (most recent call last):
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 190, in <module>
    main()
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 179, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "time_execution.py", line 74, in <module>
    test_create_detection_from_ms()
  File "time_execution.py", line 60, in test_create_detection_from_ms
    convolved, restored, residual = imager.imaging_rascil(
  File "/home/vincenzo/Karabo-Pipeline/karabo/imaging/imager.py", line 240, in imaging_rascil
    result = continuum_imaging_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/pipelines/pipeline_skymodel_rsexecute.py", line 392, in continuum_imaging_skymodel_list_rsexecute_workflow
    ) = ical_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/pipelines/pipeline_skymodel_rsexecute.py", line 154, in ical_skymodel_list_rsexecute_workflow
    skymodel_list = deconvolve_skymodel_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/skymodel/skymodel_rsexecute.py", line 396, in deconvolve_skymodel_list_rsexecute_workflow
    deconvolve_model_imagelist = deconvolve_list_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 510, in deconvolve_list_rsexecute_workflow
    return deconvolve_list_singlefacet_rsexecute_workflow(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 457, in deconvolve_list_singlefacet_rsexecute_workflow
    clean_list = rsexecute.execute(imaging_deconvolve, nout=len(dirty_list))(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/workflows/rsexecute/imaging/imaging_rsexecute.py", line 446, in imaging_deconvolve
    comp, _ = deconvolve_list(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/processing_components/image/deconvolution.py", line 128, in deconvolve_list
    check_psf_peak(psf_list)
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/rascil/processing_components/image/deconvolution.py", line 170, in check_psf_peak
    numpy.testing.assert_approx_equal(
  File "/home/vincenzo/miniconda3/envs/karabo_dev_env_rascil_7/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 698, in assert_approx_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal to 6 significant digits:
check_psf_peak: PSF 0 does not have unit peak 0.9996356147582426
 ACTUAL: 0.9996356147582426
 DESIRED: 1.0
```

The function which raises the assertion error is the following:

```
def check_psf_peak(psf_list):
    """Check that all PSFs in a list have unit peak

    :param psf_list: List of PSF images
    """
    for ipsf, psf in enumerate(psf_list):
        pmax = psf["pixels"].data.max()
        numpy.testing.assert_approx_equal(
            pmax,
            1.0,
            err_msg=f"check_psf_peak: PSF {ipsf} does not have unit peak {pmax}",
            significant=6,
        )
```

Every other test of `ska-gridder-nifty-cuda` or rascils succeeds, so I want to be sure that we use the `ska-gridder-nifty-cuda` correctly

**Comment by kenfus** [comment]
In the newest version of Rascil, the test is not located in the SKA SDP: https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python/-/blob/main/src/ska_sdp_func_python/image/deconvolution.py

I will move my issue there.

**Comment by kenfus** [comment]
@deiruch How important do you think this is? Basically, GPU acceleration does not work in Rascil currently. I can fix it directly in the `ska-spd-func`.

**Comment by fschramka** [comment]
Removing the assertion is the wrong way. The gridder does not work - we track that in the  issue #349 and #360
