### ISSUE TITLE
`SkyModel.get_MIGHTEE_Sky()` works and returns the data of the MIGHTEE Sky.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#231]
Currently, `SkyModel.get_MIGHTEE_Sky()` fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vincenzo/miniconda3/envs/karabo_user/lib/python3.9/site-packages/karabo/simulation/sky_model.py", line 608, in get_MIGHTEE_Sky
    mightee = SkyModel.get_fits_catalog(path)
  File "/home/vincenzo/miniconda3/envs/karabo_user/lib/python3.9/site-packages/karabo/simulation/sky_model.py", line 347, in get_fits_catalog
    return Table.read(path)
  File "/home/vincenzo/miniconda3/envs/karabo_user/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/home/vincenzo/miniconda3/envs/karabo_user/lib/python3.9/site-packages/astropy/io/registry/core.py", line 208, in read
    format = self._get_valid_format(
  File "/home/vincenzo/miniconda3/envs/karabo_user/lib/python3.9/site-packages/astropy/io/registry/base.py", line 337, in _get_valid_format
    raise IORegistryError("Format could not be identified based on the"
astropy.io.registry.base.IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No           
               ascii.aastex  Yes   Yes            No           
                ascii.basic  Yes   Yes            No           
                  ascii.cds  Yes    No            No           
     ascii.commented_header  Yes   Yes            No           
                  ascii.csv  Yes   Yes           Yes           
              ascii.daophot  Yes    No            No           
                 ascii.ecsv  Yes   Yes           Yes           
           ascii.fast_basic  Yes   Yes            No           
ascii.fast_commented_header  Yes   Yes            No           
             ascii.fast_csv  Yes   Yes            No           
       ascii.fast_no_header  Yes   Yes            No           
             ascii.fast_rdb  Yes   Yes            No           
             ascii.fast_tab  Yes   Yes            No           
          ascii.fixed_width  Yes   Yes            No           
ascii.fixed_width_no_header  Yes   Yes            No           
 ascii.fixed_width_two_line  Yes   Yes            No           
                 ascii.html  Yes   Yes           Yes           
                 ascii.ipac  Yes   Yes            No           
                ascii.latex  Yes   Yes           Yes           
                  ascii.mrt  Yes   Yes            No           
            ascii.no_header  Yes   Yes            No           
                  ascii.qdp  Yes   Yes           Yes           
                  ascii.rdb  Yes   Yes           Yes           
                  ascii.rst  Yes   Yes            No           
           ascii.sextractor  Yes    No            No           
                  ascii.tab  Yes   Yes            No           
                       asdf  Yes   Yes           Yes           
                       fits  Yes   Yes           Yes           
                       hdf5  Yes   Yes           Yes           
                 pandas.csv  Yes   Yes            No           
                 pandas.fwf  Yes    No            No           
                pandas.html  Yes   Yes            No           
                pandas.json  Yes   Yes            No           
                    parquet  Yes   Yes           Yes           
                    votable  Yes   Yes           Yes           
                     aastex  Yes   Yes            No        Yes
                        cds  Yes    No            No        Yes
                        csv  Yes   Yes            No        Yes
                    daophot  Yes    No            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        mrt  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
```

This was requested by Jennifer Studer.

**Comment by rohitcbscient** [comment]
Fixed it in the new #254 pull request.
