### ISSUE TITLE
Create solution to run `karabo` reliably with Slurm

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#334]
Currently, if you run a Karabo-Script on Slurm with N nodes, it runs the script parallel on the 4 nodes, instead of using the 4 nodes for e.g. Dask or some GPU parallelization

- [ ] When Karabo is run with slurm on N nodes, the script is not run Nx but uses the N nodes for parallelisation. 

Some ideas to reach that are:

- Check in the init file on which SLURMD_NODENAME it is running. If the node is not 0, the job is halted and the node is made available to dask. With SLURM_NODELIST communication via dask can be reached.
- Maybe with the parameter ntask=1 we can skip complex implementation and only describe this in the documentation.

**Comment by kenfus** [comment]
After a day of hitting my head against the wall, I have now this:

```
import os
import sys
import time
from subprocess import call

from dask.distributed import Client, LocalCluster, Worker, get_client, get_worker, wait


def get_lowest_node_id():
    return int(os.getenv('SLURM_JOB_NODELIST').split('[')[1].split('-')[0])

def get_lowest_node_name():
    return os.getenv('SLURM_JOB_NODELIST').split('[')[0] + str(get_lowest_node_id())

def create_list_of_node_names():
    return [os.getenv('SLURM_JOB_NODELIST').split('[')[0] + str(i) for i in range(get_lowest_node_id(), get_lowest_node_id() + int(os.getenv('SLURM_JOB_NUM_NODES')))]

def get_node_id():
    len_id = len(str(get_lowest_node_id()))
    return int(os.getenv('SLURMD_NODENAME')[-len_id:])

def is_first_node():
    return get_node_id() == get_lowest_node_id()

def subtract_one(x):
    print(f'Node Name = {os.getenv("SLURMD_NODENAME")}. Sleeping for 3 seconds. Current Time = {get_current_time()}')
    time.sleep(3)
    return x - 1

def get_current_time():
    return time.strftime("%H:%M:%S", time.localtime())

if __name__ == '__main__':
    if is_first_node():
        # Create client and scheduler
        cluster = LocalCluster(ip=get_lowest_node_name())
        cluster.scale(int(os.getenv('SLURM_JOB_NUM_NODES')))
        client = Client(cluster)
        print(f'Main Node. Name = {os.getenv("SLURMD_NODENAME")}. Client = {client}')
        # Write IP to file
        if os.path.exists('scheduler.txt'):
            os.remove('scheduler.txt')
        with open('scheduler.txt', 'w') as f:
            print(f'Scheduler Adress: {cluster.scheduler_address}')
            f.write(cluster.scheduler_address)
            
        # Wait that all workers are connected
        time.sleep(5)
        print(client.scheduler_info()['workers'].keys())
        while len(client.scheduler_info()['workers']) != int(os.getenv('SLURM_JOB_NUM_NODES')):
            time.sleep(1)
        # Send futures to workers
        futures = client.map(subtract_one, range(10))

        # Wait for futures to finish
        wait(futures)
        print(f'Finished. Current Time = {get_current_time()}')
        # Print results
        print(client.gather(futures))
        # Close client and cluster
        client.close() 
        cluster.close()
        # Delete scheduler file
        os.remove('scheduler.txt')


         
    else:
        # Start node as worker but sleep first a bit
        time.sleep(5)
        while True:
            try:
                with open('scheduler.txt', 'r') as f:
                    scheduler_address = f.read()
                break
            except FileNotFoundError:
                time.sleep(1)

        COMMAND = ['dask-worker', scheduler_address]
        call(COMMAND)
```

Which gives with the following command: `srun -A "sk05" -C "gpu" -p "debug" --nodes 3 --ntasks-per-core=1 --ntasks-per-node=1 --cpus-per-task=1 --hint=nomultithread python slurm.py`

The following output:

```
(dask_slurm_test) vtimmel@daint106:~> srun -A "sk05" -C "gpu" -p "debug" --nodes 3 --ntasks-per-core=1 --ntasks-per-node=1 --cpus-per-task=1 --hint=nomultithread python slurm.py
srun: job 45080598 queued and waiting for resources
srun: job 45080598 has been allocated resources
2023-03-01 18:15:25,049 - distributed.nanny - INFO -         Start Nanny at: 'tcp://148.187.41.72:36933'
2023-03-01 18:15:25,049 - distributed.nanny - INFO -         Start Nanny at: 'tcp://148.187.41.73:37621'
2023-03-01 18:15:28,178 - distributed.worker - INFO -       Start worker at:  tcp://148.187.41.72:34037
2023-03-01 18:15:28,178 - distributed.worker - INFO -          Listening to:  tcp://148.187.41.72:34037
2023-03-01 18:15:28,178 - distributed.worker - INFO -          dashboard at:        148.187.41.72:38019
2023-03-01 18:15:28,178 - distributed.worker - INFO - Waiting to connect to:  tcp://148.187.41.71:33667
2023-03-01 18:15:28,178 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,178 - distributed.worker - INFO -               Threads:                          2
2023-03-01 18:15:28,178 - distributed.worker - INFO -                Memory:                  59.57 GiB
2023-03-01 18:15:28,178 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-p18ffkaf
2023-03-01 18:15:28,178 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,178 - distributed.worker - INFO -       Start worker at:  tcp://148.187.41.73:36637
2023-03-01 18:15:28,178 - distributed.worker - INFO -          Listening to:  tcp://148.187.41.73:36637
2023-03-01 18:15:28,178 - distributed.worker - INFO -          dashboard at:        148.187.41.73:36735
2023-03-01 18:15:28,178 - distributed.worker - INFO - Waiting to connect to:  tcp://148.187.41.71:33667
2023-03-01 18:15:28,178 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,179 - distributed.worker - INFO -               Threads:                          2
2023-03-01 18:15:28,179 - distributed.worker - INFO -                Memory:                  59.57 GiB
2023-03-01 18:15:28,179 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-oz2k5vrn
2023-03-01 18:15:28,179 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,198 - distributed.worker - INFO -         Registered to:  tcp://148.187.41.71:33667
2023-03-01 18:15:28,198 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,199 - distributed.worker - INFO -         Registered to:  tcp://148.187.41.71:33667
2023-03-01 18:15:28,200 - distributed.core - INFO - Starting established connection
2023-03-01 18:15:28,200 - distributed.worker - INFO - -------------------------------------------------
2023-03-01 18:15:28,201 - distributed.core - INFO - Starting established connection
Node Name = nid02356. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02356. Sleeping for 3 seconds. Current Time = 18:15:32
Node Name = nid02356. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02356. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02356. Sleeping for 3 seconds. Current Time = 18:15:32
2023-03-01 18:15:36,108 - distributed.worker - INFO - Stopping worker at tcp://148.187.41.73:36637
2023-03-01 18:15:36,108 - distributed.worker - INFO - Stopping worker at tcp://148.187.41.72:34037
2023-03-01 18:15:36,109 - distributed.worker - INFO - Connection to scheduler broken. Closing without reporting. ID: Worker-5a96e35f-7713-4c8e-8cdf-749d1ee44635 Address tcp://148.187.41.73:36637 Status: Status.closing
2023-03-01 18:15:36,109 - distributed.worker - INFO - Connection to scheduler broken. Closing without reporting. ID: Worker-8ec514c8-0866-4506-9fc7-d1956782fdb9 Address tcp://148.187.41.72:34037 Status: Status.closing
Main Node. Name = nid02356. Client = <Client: 'tcp://148.187.41.71:33667' processes=3 threads=3, memory=89.36 GiB>
Scheduler Adress: tcp://148.187.41.71:33667
dict_keys(['tcp://148.187.41.71:42825', 'tcp://148.187.41.71:44441', 'tcp://148.187.41.71:45695'])
Finished. Current Time = 18:15:35
[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
2023-03-01 18:15:36,109 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://148.187.41.73:43552 remote=tcp://148.187.41.71:33667>
Traceback (most recent call last):
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/distributed/batched.py", line 97, in _background_send
    nbytes = yield self.comm.write(
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 267, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-03-01 18:15:36,109 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://148.187.41.72:35902 remote=tcp://148.187.41.71:33667>
Traceback (most recent call last):
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/distributed/batched.py", line 97, in _background_send
    nbytes = yield self.comm.write(
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/users/vtimmel/miniconda3/envs/dask_slurm_test/lib/python3.9/site-packages/distributed/comm/tcp.py", line 267, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-03-01 18:15:36,146 - distributed.nanny - INFO - Worker closed
2023-03-01 18:15:36,146 - distributed.nanny - INFO - Worker closed
Node Name = nid02358. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02358. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02357. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02357. Sleeping for 3 seconds. Current Time = 18:15:29
Node Name = nid02357. Sleeping for 3 seconds. Current Time = 18:15:32
2023-03-01 18:15:36,275 - distributed.nanny - INFO - Closing Nanny at 'tcp://148.187.41.73:37621'.
2023-03-01 18:15:36,275 - distributed.nanny - INFO - Closing Nanny at 'tcp://148.187.41.72:36933'.
2023-03-01 18:15:36,276 - distributed.dask_worker - INFO - End worker
2023-03-01 18:15:36,276 - distributed.dask_worker - INFO - End worker
```

So, it seems to work somehow but we can look at it on Friday!

**Comment by kenfus** [comment]
Together with @UeliDeSchwert, we created this:

import os
import time
from datetime import datetime
from random import random

from dask.distributed import Client
from dask_mpi import initialize
from mpi4py import MPI


```
def get_current_time():
    return time.strftime("%H:%M:%S", time.localtime())

def slow_is_prime(num):
    print(f'Calculating {num} on node {os.getenv("SLURMD_NODENAME")} at {get_current_time()}')
    #time.sleep(random())
    if num == 1:
        return False
    for test_factor in range(2, num // 2):
        if num % test_factor == 0:
            return False

    return True

def get_current_time():
    return time.strftime("%H:%M:%S", time.localtime())

if __name__ == '__main__':
    num_threads = int(os.environ.get(
        'SLURM_CPUS_PER_TASK',
        os.environ.get('OMP_NUM_THREADS', 1)
    ))
    initialize(nthreads=num_threads, comm=MPI.COMM_WORLD)
    client = Client()
    start_time = datetime.now()
    # Print the number of workers
    print(f'Number of workers: {len(client.scheduler_info()["workers"])}')
    # Prime between two numbers
    low = 1
    high = 100000
    num_primes = sum(
        client.gather(
            client.map(slow_is_prime, range(low, high))
        )
    )
    end_time = datetime.now()
    print(f'{num_primes} primes between {low} and {high}. Time taken: {end_time - start_time}]. NNodes: {os.getenv("SLURM_JOB_NUM_NODES")}, NThreads: {num_threads}')
```

This is how to submit it:

```
#!/bin/bash -l
#SBATCH --job-name="slurm_dask_test"
#SBATCH --account="sk05"
#SBATCH --time=00:02:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1
source slurm_dask_test/bin/activate
module load cray-mpich
srun python3 slurm_cluster.py
```

You need to carefully create a `venv` as following:

```
module load daint-gpu
module load cray-mpich
python -m venv --system-site-packages slurm_dask_test
source ./myvenv/bin/slurm_dask_test
pip install pyyaml
pip install "dask[distributed]" --upgrade
pip install dask_mpi
```

Then it should work!

**Comment by deiruch** [comment]
Ah, using MPI is a clever solution!

We should make sure there is a graceful fallback. Identical code should scale automatically from my small desktop machine without MPI to a multi-node CSCS MPI cluster.

**Comment by kenfus** [comment]
Update on the usage of slurm for karabo. Currently, it fails with the following errors:

```
Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid02358:15767] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid02359:07554] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid02359:07549] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid02359:07555] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: nid02358: tasks 12-23: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=45424723.0
srun: error: nid02359: tasks 24-35: Exited with exit code 1
srun: error: nid02357: tasks 0-11: Exited with exit code 1
```

**Comment by kenfus** [comment]
With @fschramka and @simonmarcin, we talked about an alternative solution:

```
from dask.distributed import Client
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(
    queue="debug",
    cores=12, 
    memory="64GB",
    account="sk05",
    walltime="00:30:00",
    job_extra_directives=["--constraint=gpu"],
)
cluster.scale(jobs=4)  # ask for N nodes

client = Client(cluster)

...
```

This would be submitted to one node, which starts other nodes and then uses those nodes to parallizework. This would allow us to scale the number of workers up and down, based on demand. 

Sadly, it seems that CSCS does not allow this:

```
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<_wrap_awaitable() done, defined at /users/vtimmel/.local/lib/python3.9/site-packages/distributed/deploy/spec.py:118> exception=RuntimeError("Command exited with non-zero exit code.\nExit code: 1\nCommand:\nsbatch /tmp/tmpon0kg7z0.sh\nstdout:\n\nstderr:\nsbatch: error: QOSMaxSubmitJobPerUserLimit\nsbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)\n\n")>
Traceback (most recent call last):
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 119, in _wrap_awaitable
    return await aw
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 68, in _
    await self.start()
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/dask_jobqueue/core.py", line 411, in start
    out = await self._submit_job(fn)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/dask_jobqueue/core.py", line 394, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/dask_jobqueue/core.py", line 489, in _call
    raise RuntimeError(
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
sbatch /tmp/tmpon0kg7z0.sh
stdout:

stderr:
sbatch: error: QOSMaxSubmitJobPerUserLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
```

So it seems that the solution currently implemented seems to be the best, at least until we can make the MPI one work.

**Comment by UeliDeSchwert** [comment]
I failed to find a "--account" specified in the example above. Which cscs account does this use, and for which resources is this account allowed? 
Also, does the same happen when running on the "normal" queue instead of the debug queue?

**Comment by kenfus** [comment]
I did not try it on the normal queue. You think that could work? 

`account="sk05",` Or did you mean something else?
