### ISSUE TITLE
`ERROR: testSimpleInstance (test.test_pinocchio.TestPinocchio)` does not fail with the nightly build

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#336]
```
======================================================================
ERROR: testSimpleInstance (test.test_pinocchio.TestPinocchio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Karabo-Pipeline/Karabo-Pipeline/karabo/test/test_pinocchio.py", line 22, in testSimpleInstance
    p = Pinocchio()
  File "/home/runner/work/Karabo-Pipeline/Karabo-Pipeline/karabo/simulation/pinocchio.py", line 76, in __init__
    self.currConfig = self.__loadPinocchioDefaultConfig()
  File "/home/runner/work/Karabo-Pipeline/Karabo-Pipeline/karabo/simulation/pinocchio.py", line 163, in __loadPinocchioDefaultConfig
    return Pinocchio.loadPinocchioConfig(self.paramsInputPath)
  File "/home/runner/work/Karabo-Pipeline/Karabo-Pipeline/karabo/simulation/pinocchio.py", line 178, in loadPinocchioConfig
    with open(path) as configF:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/miniconda3/envs/test_karabo/etc/pinocchio_params.conf'
```

**Comment by kenfus** [comment]
It somehow started installing the wrong Pinocchio again:  `pinocchio                             2.6.0  py39hbcdfc36_0          conda-forge/linux-64                    4MB`

**Comment by kenfus** [comment]
```
(karabo-env) vincenzo@Vincenzo-Dell:~/karabo_user$ conda update -c i4ds pinocchio
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
i4ds/linux-64                                                 No change
nvidia/label/cuda-11.7.0/linux-64                             No change
nvidia/label/cuda-11.7.0/noarch                               No change
i4ds/noarch                                                   No change
Collect all metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/vincenzo/miniconda3/envs/karabo-env

  added / updated specs:
    - pinocchio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    assimp-5.2.4               |       h4c92fa2_0         3.8 MB  conda-forge
    hpp-fcl-2.1.2              |   py39h76655d1_1         1.6 MB  conda-forge
    llvm-openmp-15.0.7         |       h0cdce71_0         3.1 MB  conda-forge
    pinocchio-2.6.9            |   py39h42d6fa7_1         4.4 MB  conda-forge
    urdfdom-3.1.0              |       h068d047_1         133 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        13.0 MB

The following NEW packages will be INSTALLED:

  llvm-openmp        conda-forge/linux-64::llvm-openmp-15.0.7-h0cdce71_0 

The following packages will be UPDATED:

  assimp                                   5.0.1-hedfc422_7 --> 5.2.4-h4c92fa2_0 
  hpp-fcl                              1.7.8-py39hbcdfc36_0 --> 2.1.2-py39h76655d1_1 
  pinocchio                            2.6.0-py39hbcdfc36_0 --> 2.6.9-py39h42d6fa7_1 
  urdfdom                                  2.3.5-h4bd325d_0 --> 3.1.0-h068d047_1 

The following packages will be DOWNGRADED:

  _openmp_mutex                                   4.5-2_gnu --> 4.5-2_kmp_llvm 
```

It seems that it cannot find `pinocchio` on the i4ds-channel?

**Comment by deiruch** [comment]
@fschramka should know more...

**Comment by kenfus** [comment]
`conda install -c i4ds pinocchio` leads to this output:

```
(karabo-env) vincenzo@Vincenzo-Dell:~/karabo_user$ conda install -c i4ds pinocchio
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
default/noarch                                                No change
default/linux-64                                              No change
i4ds/linux-64                                                 No change
i4ds/noarch                                                   No change
Collect all metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/vincenzo/miniconda3/envs/karabo-env

  added / updated specs:
    - pinocchio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    assimp-5.0.1               |       hedfc422_7         4.4 MB  conda-forge
    console_bridge-1.0.2       |       h924138e_1          18 KB  conda-forge
    eigenpy-2.7.13             |   py39h42d6fa7_0         1.6 MB  conda-forge
    hpp-fcl-1.7.8              |   py39hbcdfc36_0         2.0 MB  conda-forge
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    octomap-1.9.8              |       h924138e_0         258 KB  conda-forge
    pinocchio-2.6.0            |   py39hbcdfc36_0         3.9 MB  conda-forge
    python_abi-3.9             |           3_cp39           6 KB  conda-forge
    qhull-2020.2               |       h4bd325d_2         1.9 MB  conda-forge
    tinyxml-2.6.2              |       h4bd325d_2          55 KB  conda-forge
    urdfdom-2.3.5              |       h4bd325d_0         124 KB  conda-forge
    urdfdom_headers-1.1.0      |       h924138e_0          18 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        14.3 MB

The following NEW packages will be INSTALLED:

  assimp             conda-forge/linux-64::assimp-5.0.1-hedfc422_7 
  boost              conda-forge/linux-64::boost-1.74.0-py39h5472131_5 
  boost-cpp          conda-forge/linux-64::boost-cpp-1.74.0-h75c5d50_8 
  console_bridge     conda-forge/linux-64::console_bridge-1.0.2-h924138e_1 
  eigen              conda-forge/linux-64::eigen-3.4.0-h4bd325d_0 
  eigenpy            conda-forge/linux-64::eigenpy-2.7.13-py39h42d6fa7_0 
  hpp-fcl            conda-forge/linux-64::hpp-fcl-1.7.8-py39hbcdfc36_0 
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0 
  libblas            conda-forge/linux-64::libblas-3.9.0-16_linux64_openblas 
  libcblas           conda-forge/linux-64::libcblas-3.9.0-16_linux64_openblas 
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-12.2.0-h69a702a_19 
  libgfortran5       conda-forge/linux-64::libgfortran5-12.2.0-h337968e_19 
  liblapack          conda-forge/linux-64::liblapack-3.9.0-16_linux64_openblas 
  libopenblas        conda-forge/linux-64::libopenblas-0.3.21-pthreads_h78a6416_3 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.2.0-h46fd767_19 
  numpy              conda-forge/linux-64::numpy-1.24.2-py39h7360e5f_0 
  octomap            conda-forge/linux-64::octomap-1.9.8-h924138e_0 
  pinocchio          conda-forge/linux-64::pinocchio-2.6.0-py39hbcdfc36_0 
  python_abi         conda-forge/linux-64::python_abi-3.9-3_cp39 
  qhull              conda-forge/linux-64::qhull-2020.2-h4bd325d_2 
  tinyxml            conda-forge/linux-64::tinyxml-2.6.2-h4bd325d_2 
  urdfdom            conda-forge/linux-64::urdfdom-2.3.5-h4bd325d_0 
  urdfdom_headers    conda-forge/linux-64::urdfdom_headers-1.1.0-h924138e_0 
  zlib               conda-forge/linux-64::zlib-1.2.13-h166bdaf_4 
  zstd               conda-forge/linux-64::zstd-1.5.2-h3eb15da_6 


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```
My channels: 

```
(karabo-env) vincenzo@Vincenzo-Dell:~/karabo_user$ conda config --get channels
--add channels 'default'   # lowest priority
--add channels 'conda-forge'
--add channels 'i4ds'   # highest priority
```

Very weird.. Maybe there is a reason the libmamba-solver is experimental.

**Comment by deiruch** [comment]
We/everyone should probably use `--strict-channel-priority` anyway... (see https://docs.conda.io/projects/conda/en/latest/commands/install.html)

**Comment by kenfus** [comment]
Aha, something new: 

```
(karabo-env) vincenzo@Vincenzo-Dell:~/karabo_user$ conda install pinocchio -c i4ds --strict-channel-priority
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be string, but is null
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not parse state fileCould not load cache state: [json.exception.type_error.302] type must be string, but is null
i4ds/noarch                                          1.7kB @   4.7kB/s  0.4s
i4ds/linux-64                                        2.3kB @   5.2kB/s  0.5s
default/linux-64                                   139.0 B @ 223.0 B/s  0.6s
default/noarch                                     130.0 B @ 200.0 B/s  0.6s
Collect all metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides fftw3 needed by pinocchio-5.0.0-h3fd9d12_0
```

I guess I leave this then to @fschramka

**Comment by fschramka** [comment]
`conda install -c i4ds fftw3` is the wrong call

there is no '3' in the official package - hence we dropped the 3 as well. 

try it with:
`conda install -c i4ds/label/rel_v14 fftw`

**Comment by fschramka** [comment]
Does this work now? Can we close this?

**Comment by kenfus** [comment]
Nightly build still fails. I think it should be fixed when #348  is merged

**Comment by Lukas113** [comment]
Not sure about that, I haven't done any significant work on the nightly builds. This issue should be resolved since the PR #356 .

**Comment by Lukas113** [comment]
Hmm, I think we can close this issue since #370 should take care of this if this bug still occurs.

**Comment by kenfus** [comment]
I agree!
