### ISSUE TITLE
Dask `client` is generated as a global variable in the `__init__` of Karabo

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#385]
This makes karabo easier to use.

**Comment by kenfus** [comment]
When using client(processes=False), same error:


```
/users/vtimmel/.local/lib/python3.9/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37437 instead
  warnings.warn(
2023-04-14 16:03:14,110 - distributed.nanny - ERROR - Failed to start process
Traceback (most recent call last):
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/nanny.py", line 442, in instantiate
    result = await self.process.start()
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/nanny.py", line 711, in start
    await self.process.start()
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/users/vtimmel/.local/lib/python3.9/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by kenfus** [comment]
Yes, it's stale.
