### ISSUE TITLE
`Visibility.combine_vis` can handle different cunks of a SkyModel

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#402]
It should be able to handle:
- If the SkyModel is split up randomly
- If the Observation is split up, e.g. by channel.

Currently, when generating random sources, the `Imager` fails with the following error:

```
Traceback (most recent call last):
  File "/users/vtimmel/karabo/Karabo-Pipeline/karabo/examples/time_karabo.py", line 156, in <module>
    main(n_random_sources=200000)
  File "/users/vtimmel/karabo/Karabo-Pipeline/karabo/examples/time_karabo.py", line 104, in main
    deconvolved, restored, residual = imager_askap.imaging_rascil(
  File "/users/vtimmel/karabo/Karabo-Pipeline/karabo/imaging/imager.py", line 224, in imaging_rascil
    blockviss = create_visibility_from_ms_rsexecute(
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/rascil/workflows/rsexecute/visibility/visibility_rsexecute.py", line 46, in create_visibility_from_ms_rsexecute
    [
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/rascil/workflows/rsexecute/visibility/visibility_rsexecute.py", line 47, in <listcomp>
    rsexecute.execute(create_visibility_from_ms, nout=nout)(
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/rascil/processing_components/visibility/base.py", line 465, in create_visibility_from_ms
    ms_vis = ms.getcolslice(datacolumn, blc=blc, trc=trc)
  File "/users/vtimmel/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/casacore/tables/table.py", line 1077, in getcolslice
    return self._getcolslice(columnname, blc, trc, inc,
RuntimeError: Slicer error:infer: startResult>=shape

```

When using a real sky, this does not happen. We should make sure that this error is OK, because it's random sources and not that it is an error by combining the visibilities.

**Comment by kenfus** [comment]
Consitent result, should be checked by a test. 

@kenfus will send @rohitcbscient visiblities generated by karabo parallelisation.

**Comment by rohitcbscient** [comment]
The idea of using chunks in the skymodel should be motivated by user science case, not a general feature.
